### ISSUE TITLE
TypeError after successful action

### ISSUE THREAD

**Issue by SmartALB** [zerostep-ai/zerostep#30]
Hello!
We are very excited about this project.
During my test runs, I notice that it is not yet completely stable.

While this action is performed without any problems:
![image](https://github.com/zerostep-ai/zerostep/assets/139439933/bffa8378-c1ca-45e2-bba9-beed2b48b72b)
![image](https://github.com/zerostep-ai/zerostep/assets/139439933/4f50bb60-8269-43f4-9eba-18b015020112)
` await ai("Click on a day", { page: appointmentManagerPage, test })`

This error is thrown after successfully(!) performing this action:
![image](https://github.com/zerostep-ai/zerostep/assets/139439933/ff9a84a7-fdd4-4e32-a831-e99da6e313aa)
![image](https://github.com/zerostep-ai/zerostep/assets/139439933/a610dc90-eaaf-4251-be9d-f5107beed609)

`await ai("Click on a time slot", { page: appointmentManagerPage, test })`

` TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
        at Object.getContentQuads (r:\Sources\...\Playwright\node_modules\@zerostep\playwright\src\cdp.ts:208:7)
        at Object.clickCDPElement (r:\Sources\...\Playwright\node_modules\@zerostep\playwright\src\playwright.ts:11:32)
        at executeCommand (r:\Sources\...\Playwright\node_modules\@zerostep\playwright\src\index.ts:210:14)
        at r:\Sources\...\Playwright\node_modules\@zerostep\playwright\src\index.ts:147:30`

**Comment by tmcneal** [comment]
Thank you for reporting @SmartALB - we will take a look and report back on what we find!

**Comment by MitchHub** [comment]
Hi @SmartALB,

Thank you for bringing this to our attention. I am one of the developers at ZeroStep and I am investigating what the issue is here. It would be very helpful if I could reproduce the issue myself - would that be possible? If this appointment manager site is publicly accessible, would you mind sharing the full Playwright test where you saw this problem occurring?

**Comment by SmartALB** [comment]
> Hi @SmartALB,
> 
> Thank you for bringing this to our attention. I am one of the developers at ZeroStep and I am investigating what the issue is here. It would be very helpful if I could reproduce the issue myself - would that be possible? If this appointment manager site is publicly accessible, would you mind sharing the full Playwright test where you saw this problem occurring?

Hi! Sure. I can send you the url of an calendar off this channel (discord?)

**Comment by MitchHub** [comment]
I received your DM on discord. I will take a look and let you know what I find. Thanks!

**Comment by khsheehan** [comment]
Hey @SmartALB

At the moment, this is a shortcoming of our AI. The issue is that the page changes in a way that isn't expected and so while we successfully execute the action as described, we try (and fail) to execute another action. Until improvements to our AI are shipped that address this, you can reword the prompt so that it doesn't fail. We've found that `"Click on the first time slot"` works, and is more a predictable action anyway.

Thanks for bringing this to our attention, and hope this helps!
